"""Init

Revision ID: 0cb882648211
Revises: 
Create Date: 2024-04-07 11:06:37.725333

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0cb882648211'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
